const animals = [
    {name: 'GIANT PANDAS',
     location: 'Native to Southwest China',
    image: '../../assets/images/pandas.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'EAGLES',
     location: 'Native to South America',
    image: '../../assets/images/eagle.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'GORILLAS',
     location: 'Native to Congo',
    image: '../../assets/images/gorilla.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'TWO-TOED SLOTH',
     location: 'Mesoamerica, South America',
    image: '../../assets/images/sloth.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'CHEETAHS',
     location: 'Native to Africa',
    image: '../../assets/images/cheetahs.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'PENGUINS',
     location: 'Native to Antarctica',
    image: '../../assets/images/pinguin.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'FOX',
     location: 'all of Europe',
    image: '../../assets/images/fox.jpg', 
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'PRZEWALSKI HORSE',
     location: 'western Mongolia',
    image: '../../assets/images/horse_prj.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'HYENA',
     location: 'Native to Africa',
    image: '../../assets/images/hyena.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'JERBOA',
     location: 'Asia west',
    image: '../../assets/images/jerboa.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'KENGURU',
     location: 'Native to Australia',
    image: '../../assets/images/kenguru.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'OWL',
     location: 'Native to Europe',
    image: '../../assets/images/owl.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'PUMA',
     location: 'Native to America',
    image: '../../assets/images/puma.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"},
    {name: 'ZUBR',
     location: 'Native to Eastern Europe',
    image: '../../assets/images/zubr.jpg',
    diet: 'herbivorous',
    meal: "../../assets/icons/herbivorous_icon.svg"},
    {name: 'WOLF',
     location: 'Native to Europe',
    image: '../../assets/images/wolf.jpg',
    diet: 'predatory',
    meal: "../../assets/icons/predatory_icon.svg"}
]
export default animals